cmake_minimum_required(VERSION 3.15)

if (CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
    list(APPEND CMAKE_PREFIX_PATH ${PROJECT_SOURCE_DIR}/GLFW/MinGW-x86_64-8.1.0/${CMAKE_BUILD_TYPE}/lib/cmake/glfw3)
elseif (CMAKE_CXX_COMPILER_ID STREQUAL "Clang" OR CMAKE_CXX_COMPILER_ID STREQUAL "AppleClang")
    if (CMAKE_CXX_COMPILER_FRONTEND_VARIANT STREQUAL "MSVC")
        list(APPEND CMAKE_PREFIX_PATH ${PROJECT_SOURCE_DIR}/GLFW/Clang-VS2019-x86_64/${CMAKE_BUILD_TYPE}/lib/cmake/glfw3)
    elseif (CMAKE_CXX_COMPILER_FRONTEND_VARIANT STREQUAL "GNU")
        list(APPEND CMAKE_PREFIX_PATH ${PROJECT_SOURCE_DIR}/GLFW/Clang-13-MinGW-11.2.0_x64/${CMAKE_BUILD_TYPE}/lib/cmake/glfw3)
    endif ()
endif ()

# Get packages
find_package(glfw3 CONFIG REQUIRED)